The job offers are from the techmap jobs from Kaggle, this notebook shows how it was cleaned to be used after

# Import the data
This should take some minutes to run as the file is pretty big (more than 4GO)

In [6]:
import pandas as pd
import json
raw_data_url='../data/raw/techmap-jobs_us_2023-05-05.json'
def json_generator(file_path):
    with open(file_path,encoding='latin-1') as file:
        for line in file:
            yield json.loads(line)

df = pd.DataFrame(json_generator(raw_data_url))

In [7]:
df.head()

,_id,sourceCC,source,idInSource,locationID,companyID,text,html,json,locale,...,dateMerged,dateUploaded,dateCreated,orgTags,contact,salary,referenceID,dateExpired,lastUpdated,datesUpdated
0,{'$oid': '6457879fd1187d621cbbba9c'},us,aarp_us,5746ace7615e704670c93f4ac331db83b,{'$oid': '615c9811370ba62732cb7ac6'},{'$oid': '611704bf95084c5cced43d52'},"At Legacy Risk, an Alera Group Company, our bu...","<p>At Legacy Risk, an Alera Group Company, our...",{'schemaOrg': {'@context': 'http://schema.org'...,en_US,...,{'$date': '2000-01-01T00:00:00Z'},{'$date': '2023-05-07T11:12:31.658Z'},{'$date': '2023-05-05T00:00:00Z'},{'CATEGORIES': ['Advertising/Public Relations']},NaN,NaN,NaN,NaN,NaN,NaN
1,{'$oid': '6457887cd1187d621cbbbae1'},us,aarp_us,3706ea9b3e281d34db63f020269d6f7bb,{'$oid': '6457887cd1187d621cbbbae2'},{'$oid': '60e4e449a25b113ad740558e'},DescriptionWe are looking for music educators ...,DescriptionWe are looking for music educators ...,{'schemaOrg': {'@context': 'http://schema.org'...,en_US,...,{'$date': '2000-01-01T00:00:00Z'},{'$date': '2023-05-07T11:16:12.271Z'},{'$date': '2023-05-05T00:00:00Z'},{'CATEGORIES': ['Arts/Entertainment/Publishing']},NaN,NaN,NaN,NaN,NaN,NaN
2,{'$oid': '6457889ad1187d621cbbbb01'},us,aarp_us,94839fc51fd4ac9ed7e175287b5e51f9b,{'$oid': '6457889ad1187d621cbbbb02'},{'$oid': '61b97b9320b1040fa42e1b8d'},To provide excellent guest service by performi...,To provide excellent guest service by performi...,{'schemaOrg': {'@context': 'http://schema.org'...,en_US,...,{'$date': '2000-01-01T00:00:00Z'},{'$date': '2023-05-07T11:16:42.663Z'},{'$date': '2023-05-05T00:00:00Z'},{'CATEGORIES': ['Arts/Entertainment/Publishing']},NaN,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '645788afd1187d621cbbbb23'},us,aarp_us,b034a66611ec1ba6a967c6eec60fc8e4b,{'$oid': '63e53313cda3d078b3ff8d53'},{'$oid': '61088c2df7521e4ae71be309'},What exactly is a search engine evaluation job...,<strong>What exactly is a search engine evalua...,{'schemaOrg': {'@context': 'http://schema.org'...,en_US,...,{'$date': '2000-01-01T00:00:00Z'},{'$date': '2023-05-07T11:17:03.53Z'},{'$date': '2023-05-05T00:00:00Z'},{'CATEGORIES': ['Arts/Entertainment/Publishing']},NaN,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '645788b4d1187d621cbbbb25'},us,aarp_us,b1752f81f72dd63b7895dca4e92b5fd3b,{'$oid': '645788b4d1187d621cbbbb28'},{'$oid': '645788b4d1187d621cbbbb27'},We are a high-quality printing company operati...,We are a high-quality printing company operati...,{'schemaOrg': {'@context': 'http://schema.org'...,en_US,...,{'$date': '2000-01-01T00:00:00Z'},{'$date': '2023-05-07T11:17:08.569Z'},{'$date': '2023-05-05T00:00:00Z'},{'CATEGORIES': ['Arts/Entertainment/Publishing']},NaN,NaN,NaN,NaN,NaN,NaN

We can see the data is not cleaned yed and need some work, we want the final data to contain:
* Job Title
* Company Name
* Company Address
* Description of the job 
* Url of the job
* Salary (if mentionned)

In [8]:
df.columns

Index(['_id', 'sourceCC', 'source', 'idInSource', 'locationID', 'companyID',
       'text', 'html', 'json', 'locale', 'position', 'orgAddress',
       'orgCompany', 'name', 'url', 'dateScraped', 'dateMerged',
       'dateUploaded', 'dateCreated', 'orgTags', 'contact', 'salary',
       'referenceID', 'dateExpired', 'lastUpdated', 'datesUpdated'],
      dtype='object')

In [9]:
df=df.drop(columns=['companyID','_id', 'sourceCC', 'source', 'idInSource', 'locationID','html', 'json','locale','dateScraped', 'dateMerged',
       'dateUploaded', 'dateCreated', 'orgTags', 'contact','referenceID', 'dateExpired', 'lastUpdated', 'datesUpdated','salary'])

In [14]:
df['position']=df['position'].apply(lambda x: x['name'])

In [22]:
df['orgAddress']=df['orgAddress'].apply(lambda x: x['addressLine'])

In [25]:
df['orgCompany']=df['orgCompany'].apply(lambda x: x['name'])

In [31]:
def salary(x):
    try:
        return x['text']
    except:
        return x

In [32]:
df['salary']=df['salary'].apply(salary)

In [33]:
df

,text,position,orgAddress,orgCompany,name,url,salary
0,"At Legacy Risk, an Alera Group Company, our bu...",Account Manager,"Walnut Creek, CA",Alera Group,Account Manager,https://jobs.aarp.org/job/account-manager-waln...,NaN
1,DescriptionWe are looking for music educators ...,"Music Teacher, Band Director","Roselle, IL",Music and Arts,"Music Teacher, Band Director",https://jobs.aarp.org/job/music-teacher-band-d...,NaN
2,To provide excellent guest service by performi...,Floral Clerk FT Chapel Hill NC,"Chapel Hill, NC",Alex Lee,Floral Clerk FT Chapel Hill NC,https://jobs.aarp.org/job/floral-clerk-ft-chap...,NaN
3,What exactly is a search engine evaluation job...,Audio and Video Transcription - Flexible Sched...,"Lansing, IL",Appen,Audio and Video Transcription - Flexible Sched...,https://jobs.aarp.org/job/audio-and-video-tran...,NaN
4,We are a high-quality printing company operati...,Sticker Production Assistant,"Tinley Park, IL",MakeStickers,Sticker Production Assistant,https://jobs.aarp.org/job/sticker-production-a...,NaN
...,...,...,...,...,...,...,...
33059,POSITION SUMMARY: This position supports the w...,Westview Group Fitness Instructor,"Bennington, NE",Ymca of Greater Omaha,Westview Group Fitness Instructor,https://www.simplyhired.com/job/gcyhSEHTpVY7f9...,Dollar 12.12 - Dollar 19.05 an hour
33060,"Looking for an experienced groundskeeper, land...",Groundskeeper and Maintenance,"San Antonio, TX",Balanced Life Management Co.,Groundskeeper and Maintenance,https://www.simplyhired.com/job/21plypW6zpWkvX...,"Dollar 35,000 a year"
33061,Job Summary The Apps Engineering team is looki...,Data Analyst for Marketing Performance & Desig...,,"OSI Engineering, Inc.",Data Analyst for Marketing Performance & Desig...,https://www.dice.com/job-detail/4a0bc1f7-6d51-...,Dollar 60 - Dollar 70
33062,Tam-O-Shanter Country Club Job Description Pos...,Server/Banquet Server- Private Club,"West Bloomfield Township, MI",Tam-O-Shanter Country Club,Server/Banquet Server- Private Club,https://www.simplyhired.com/job/afjRIAqnrLYOjS...,Dollar 25 - Dollar 45 an hour
33063,"Description We are in search of an adept, inno...",Creative Director,"Darien, CT 06820",Waystar,Creative Director,https://www.jobs.com/en-us/jobs/creative-direc...,219800-224640 (USD per YEAR)

The data looks cleaner now and ready to be used

In [34]:
df.to_csv('../data/raw/techmap-jobs-cleaned.csv',index=False)